packages:
  - apps/*
  - packages/*
  - '!**/test/**'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nice-napi
  - puppeteer
  - sharp
