/**
 * Manually export desired components to the user.
 *
 * While `components.ts` is generated by the Vue Output Target, this file remains unchanged,
 * allowing for manual control over what components are exposed to the user.
 */
export { MyComponent, MyCounter } from './components.js'
